version: "3.5"

services:

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - 8080:8080
    volumes:
      - jenkins_vol:/var/jenkins_home

  artifactory:
    container_name: artifactory
    # xài đỡ image của bạn này
    image: goodrainapps/artifactory-oss
    # image artifactory-oss ở dưới ở dạng helm, k xài được cho 1 docker host
    # image: docker.bintray.io/jfrog/artifactory-oss
    ports:
      - 8081:8081

volumes:
  jenkins_vol:
    # có trước nên là external, nếu chưa có thì docker-compose sẽ tự tạo --> bỏ dòng dưới
    external: true
